### PR TITLE
Bump build number for rerendering

### PR DESCRIPTION
**Pull request by valeriupredoi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Hey folks, just a bogstandard rebuild trigger with bumped build number =1 so you can accommodate the new Python=3.12, so `iris` and `iris-esmf-regrid` can then be happy with `cf-units`. Please disregard if Python=3.12 is creating issues upstream (have not seen any signs of them though).

### CODE REVIEW

**Comment by valeriupredoi** [comment]
@conda-forge-admin, please rerender

**Comment by trexfeathers** [comment]
@valeriupredoi looking at the CI suggests this still isn't supporting Python 3.12. Is that your understanding too? Any ideas why?

**Comment by ocefpaf** [comment]
> Any ideas why?

The bot will issue the migration PR soon, if not we can check it's logs to see if there's anything wrong. However, during the migration period, rerendering won't add py312.

**Comment by trexfeathers** [comment]
Thanks @ocefpaf!

@valeriupredoi are you happy to wait?

**Review by trexfeathers — APPROVED** [review]

**Comment by trexfeathers** [comment]
We're gonna merge it anyway for latest NumPy support then we'll return to this for 3.12 later.

**Comment by valeriupredoi** [comment]
Hey folks, my apologies, I should have checked but @zklaus did that - it appears cf-units is not solving yet for 3.12 at http://conda-forge.org/status - could be that I jumped the gun and we should let the bot do its job? 🍺

**Comment by valeriupredoi** [comment]
just saw the merge - cheers both @trexfeathers and @ocefpaf - and my apologies if I was a bit too cavalier and didn't wait for the :robot:

**Comment by ocefpaf** [comment]
BTW, the main blocker in the migration is `antlr-python-runtime`. See https://github.com/SciTools/cf-units/issues/313 for more context.

**Comment by trexfeathers** [comment]
> BTW, the main blocker in the migration is `antlr-python-runtime`. See [SciTools/cf-units#313](https://github.com/SciTools/cf-units/issues/313) for more context.

Cool, that will be sorted at the next release (hopefully soon), then we can deal with 3.12 after that.

**Pull request merged**
