### PR TITLE
Use Azure on Windows

### PR DESCRIPTION
**Pull request by ocefpaf**

### CODE REVIEW

**Comment by bjlittle** [comment]
@ocefpaf LGTM :+1: 

Are you happy for me to merge?

**Comment by ocefpaf** [comment]
> Are you happy for me to merge?

Sorry. Clicked the button before your message showed up.

**Comment by bjlittle** [comment]
Just how strong was that :coffee: ? :smile:

**Comment by bjlittle** [comment]
All good, thanks for pushing this over the line, much appreciated :+1:

**Comment by ocefpaf** [comment]
> Just how strong was that  ?

The truth is that I use an [extension to merge](https://github.com/sindresorhus/refined-github) passing PRs, so boilerplate PRs like this one I click the merge button as soon as I issue the PR and let the browser do the rest.

**Comment by bjlittle** [comment]
Ohh nice, thanks for sharing the browser extension goodness :heart:

**Pull request merged**
