### PR TITLE
Update to v3.3.0; also removing old patches.

### PR DESCRIPTION
**Pull request by pp-mo**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pp-mo** [comment]
@conda-forge-admin, please rerender

**Comment by pp-mo** [comment]
@conda-forge-admin, please rerender

**Comment by pp-mo** [comment]
Note : I **_presume_** removing [the old patches](https://github.com/conda-forge/cf_units-feedstock/blob/591ef1df4d2cd5e693b22e4eab8d1ee718e1688b/recipe/meta.yaml#L11-L15) is now the right thing to do ?

At least, if it seems to work, then I know no better.
  * There is a note about removing the "backport_368" [here](https://github.com/conda-forge/cf_units-feedstock/pull/57#issue-1940026198)  (it's about Python 3.12 ?)
  * I can't work out if the other one is still needed (it's about numpy 2)
    Possibly, given the current failures ?

**Comment by ocefpaf** [comment]
> * There is a note about removing the "backport_368" [here](https://github.com/conda-forge/cf_units-feedstock/pull/57#issue-1940026198)  (it's about Python 3.12 ?)

That one was merged. See https://github.com/SciTools/cf-units/pull/368
The other one was not but I believe someone made the proper changes in another PR. If not, it is just https://github.com/SciTools/cf-units/pull/427/files#diff-ef037721b197e608853e2e25efd260fb32471e5e861083e0c2996fecbde976d6 that is needed.

> * I can't work out if the other one is still needed (it's about numpy 2)
>   Possibly, given the current failures ?

Nope. Just the name. PyPI is no longer accepting `-` and `_` as the same thing in URLs.

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by pp-mo** [comment]
Thanks @ocefpaf !
I hadn't seen what you did, so I made a fix, which then conflicted with yours !

**Pull request merged**
