### PR TITLE
Add @pp-mo as maintainer.

### PR DESCRIPTION
**Pull request by trexfeathers**
Checklist

N/A

### CODE REVIEW

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by trexfeathers** [comment]
@ocefpaf did I miss a spot? Do you need me to do anything?

**Comment by ocefpaf** [comment]
> @ocefpaf did I miss a spot? Do you need me to do anything?

Looks like you don't allow for others to edit your PR, so if you can re-render to add the new maintainer to the README it would be nice.

**Comment by trexfeathers** [comment]
@conda-forge-admin, please rerender

**Comment by trexfeathers** [comment]
I think something weird is going on with my fork. I'll try again...

**Pull request closed without merging**
