### PR TITLE
Build for numpy 2.0

### PR DESCRIPTION
**Pull request by ocefpaf**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by h-vetinari** [comment]
If you want, you could copy the migrators touched by https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5790 into `.ci_support/migrations` with `use_local: true` and then rerender. I've done this in https://github.com/conda-forge/pythran-feedstock/pull/84 and a couple other feedstocks, for example. Just if you want though. ;-)

**Comment by trexfeathers** [comment]
Many thanks @ocefpaf ❤

**Comment by ocefpaf** [comment]
@trexfeathers note that this is mostly for testing. I sent a PR upstream in https://github.com/SciTools/cf-units/pull/427 and the relevant commit is https://github.com/SciTools/cf-units/pull/427/commits/7fbaeebccd611242c0d711bb356723c0e2bbe0d5. Feel free to copy that over in a better PR if you want. Mine is a bit messy b/c I really cannot make heads or tails of the CI configuration there.

**Comment by trexfeathers** [comment]
@ocefpaf OK, appreciate the clarification. Hopefully @bjlittle and @pp-mo (our current cf-units leads) will be able to find some time soon 🤞

**Pull request merged**
